/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        btn_logout.setBackground(new Color(255,255,255,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_top = new javax.swing.JPanel();
        eway = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        logoUser = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        tf_search = new javax.swing.JTextField();
        logoSearch = new javax.swing.JLabel();
        sortBy = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        pn_no = new javax.swing.JPanel();
        lb_no = new javax.swing.JLabel();
        pn_time = new javax.swing.JPanel();
        lb_time = new javax.swing.JLabel();
        pn_pickup = new javax.swing.JPanel();
        lb_pickup = new javax.swing.JLabel();
        pn_send = new javax.swing.JPanel();
        lb_send = new javax.swing.JLabel();
        pn_phone = new javax.swing.JPanel();
        lb_phone = new javax.swing.JLabel();
        showNo = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        showPickup = new javax.swing.JLabel();
        showSend = new javax.swing.JLabel();
        showPhone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 58, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top.setBackground(new java.awt.Color(103, 197, 233));
        panel_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eway.setFont(new java.awt.Font("FreesiaUPC", 1, 28)); // NOI18N
        eway.setForeground(new java.awt.Color(255, 255, 255));
        eway.setText("E-WAYS");
        panel_top.add(eway, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        showName.setBackground(new java.awt.Color(204, 204, 204));
        showName.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        showName.setForeground(new java.awt.Color(153, 153, 153));
        showName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        showName.setText("name surname");
        panel_top.add(showName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 190, 20));

        logoUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\gib\\IT\\ปี1 เทอม2\\INT105 java\\Project\\icon\\user (1).png")); // NOI18N
        panel_top.add(logoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(153, 153, 153));
        btn_logout.setText("logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panel_top.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, 20));

        jPanel1.add(panel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 750, 42));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setFont(new java.awt.Font("FreesiaUPC", 1, 28)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 58, 72));
        admin.setText("Admin");
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, 73, 34));

        tf_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 58, 72)));
        jPanel2.add(tf_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 30));

        logoSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\gib\\IT\\ปี1 เทอม2\\INT105 java\\Project\\icon\\loupe.png")); // NOI18N
        jPanel2.add(logoSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        sortBy.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        sortBy.setForeground(new java.awt.Color(0, 58, 72));
        sortBy.setText("Sort by");
        jPanel2.add(sortBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        tf_date.setText("Date");
        jPanel2.add(tf_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        pn_no.setBackground(new java.awt.Color(255, 204, 0));

        lb_no.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_no.setForeground(new java.awt.Color(255, 255, 255));
        lb_no.setText("No.");

        javax.swing.GroupLayout pn_noLayout = new javax.swing.GroupLayout(pn_no);
        pn_no.setLayout(pn_noLayout);
        pn_noLayout.setHorizontalGroup(
            pn_noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_noLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_no, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_noLayout.setVerticalGroup(
            pn_noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_noLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pn_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 30));

        pn_time.setBackground(new java.awt.Color(255, 204, 0));

        lb_time.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_time.setForeground(new java.awt.Color(255, 255, 255));
        lb_time.setText("Time");

        javax.swing.GroupLayout pn_timeLayout = new javax.swing.GroupLayout(pn_time);
        pn_time.setLayout(pn_timeLayout);
        pn_timeLayout.setHorizontalGroup(
            pn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_time)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pn_timeLayout.setVerticalGroup(
            pn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_timeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pn_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, 30));

        pn_pickup.setBackground(new java.awt.Color(255, 204, 0));

        lb_pickup.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_pickup.setForeground(new java.awt.Color(255, 255, 255));
        lb_pickup.setText("Pickup Place");

        javax.swing.GroupLayout pn_pickupLayout = new javax.swing.GroupLayout(pn_pickup);
        pn_pickup.setLayout(pn_pickupLayout);
        pn_pickupLayout.setHorizontalGroup(
            pn_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pickupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pn_pickupLayout.setVerticalGroup(
            pn_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pickupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pn_pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));

        pn_send.setBackground(new java.awt.Color(255, 204, 0));

        lb_send.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_send.setForeground(new java.awt.Color(255, 255, 255));
        lb_send.setText("Send Place");

        javax.swing.GroupLayout pn_sendLayout = new javax.swing.GroupLayout(pn_send);
        pn_send.setLayout(pn_sendLayout);
        pn_sendLayout.setHorizontalGroup(
            pn_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pn_sendLayout.setVerticalGroup(
            pn_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sendLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 150, 30));

        pn_phone.setBackground(new java.awt.Color(255, 204, 0));

        lb_phone.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_phone.setForeground(new java.awt.Color(255, 255, 255));
        lb_phone.setText("Phone Number");

        javax.swing.GroupLayout pn_phoneLayout = new javax.swing.GroupLayout(pn_phone);
        pn_phone.setLayout(pn_phoneLayout);
        pn_phoneLayout.setHorizontalGroup(
            pn_phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_phoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_phoneLayout.setVerticalGroup(
            pn_phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_phoneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pn_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 170, 30));

        showNo.setBackground(new java.awt.Color(204, 204, 204));
        showNo.setFont(new java.awt.Font("TH Sarabun New", 0, 26)); // NOI18N
        showNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.add(showNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 110));

        showTime.setBackground(new java.awt.Color(204, 204, 204));
        showTime.setFont(new java.awt.Font("TH Sarabun New", 0, 26)); // NOI18N
        showTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 110, 110));

        showPickup.setBackground(new java.awt.Color(204, 204, 204));
        showPickup.setFont(new java.awt.Font("TH Sarabun New", 0, 26)); // NOI18N
        showPickup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.add(showPickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 110));

        showSend.setBackground(new java.awt.Color(204, 204, 204));
        showSend.setFont(new java.awt.Font("TH Sarabun New", 0, 26)); // NOI18N
        showSend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.add(showSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 150, 110));

        showPhone.setBackground(new java.awt.Color(204, 204, 204));
        showPhone.setFont(new java.awt.Font("TH Sarabun New", 0, 26)); // NOI18N
        showPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.add(showPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 170, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 750, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        btn_logout.setForeground(new java.awt.Color(0, 58, 72));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        btn_logout.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        //System.exit(0);
        LoginGui lgn = new LoginGui();
        lgn.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel eway;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_no;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_pickup;
    private javax.swing.JLabel lb_send;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel logoSearch;
    private javax.swing.JLabel logoUser;
    private javax.swing.JPanel panel_top;
    private javax.swing.JPanel pn_no;
    private javax.swing.JPanel pn_phone;
    private javax.swing.JPanel pn_pickup;
    private javax.swing.JPanel pn_send;
    private javax.swing.JPanel pn_time;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel showNo;
    private javax.swing.JLabel showPhone;
    private javax.swing.JLabel showPickup;
    private javax.swing.JLabel showSend;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel sortBy;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
