/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import Eway.model.ConnectionBuilder;
import Eway.model.Person;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class LoginGui extends javax.swing.JFrame {
    private Admin adHome; 
    private BookingHome home ;
    private Person person;
    /**
     * Creates new form LoginGui
     */
    public LoginGui() {
        initComponents();
        btn_exit.setBackground(new Color(255,255,255,0));
        wallpaper.setBackground(new Color(255,255,255,0));
        txt_username.setBackground(new Color(255,255,255,0));
        txt_password.setBackground(new Color(255,255,255,0));
        btn_login.setBackground(new Color(255,255,255,0));
        
        
        this.setLocationRelativeTo(null);//setให้GUIแสดงตรงกลางจอคอม
    }

    public Person getPerson() {
        return person;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallpaperLeft = new javax.swing.JLabel();
        wallpaper = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Safe Night Ride Care");
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wallpaper.setBackground(new java.awt.Color(0, 58, 72));
        wallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(240, 240, 240));
        txt_username.setFont(new java.awt.Font("TH Sarabun New", 1, 30)); // NOI18N
        txt_username.setForeground(new java.awt.Color(16, 20, 48));
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        wallpaper.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 210, 30));

        txt_password.setBackground(new java.awt.Color(240, 240, 240));
        txt_password.setFont(new java.awt.Font("TH Sarabun New", 1, 30)); // NOI18N
        txt_password.setForeground(new java.awt.Color(16, 20, 48));
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        wallpaper.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 210, 30));

        btn_login.setBackground(new java.awt.Color(0, 153, 153));
        btn_login.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        btn_login.setForeground(new java.awt.Color(16, 20, 48));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        wallpaper.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 379, 490, 50));

        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        wallpaper.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\gib\\IT\\ปี1 เทอม2\\INT105 java\\Project\\E-way-project\\src\\icon\\login.png")); // NOI18N
        wallpaper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        int i=0;
        while(i<1){
            this.person=Person.login(txt_username.getText(),txt_password.getText());
            i++;
        }
        String sql = "SELECT * FROM PERSON WHERE Person_ID =?";
        String temp;
        
        try{
            Connection con=ConnectionBuilder.getConnection();
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,""+person.getPersonId());
            ResultSet rs=pst.executeQuery();
            if (rs.next()) {
                temp = rs.getString("Person_TYPE");
                this.setVisible(false);
                if(temp.equalsIgnoreCase("student")){
                    home = new BookingHome(person);
                    home.setVisible(true);
                    System.out.println(person);
                }
                else if(temp.equalsIgnoreCase("admin")){
                    adHome = new Admin(this.person);
                    adHome.setVisible(true);
                    System.out.println(person);
                }
            }
        }catch(SQLException se){
            System.out.println(se);
        }
        
       
        
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
       int key=evt.getKeyCode();
       if(key==KeyEvent.VK_ENTER)
            txt_password.requestFocus();
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
            txt_username.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
      if(evt.getKeyCode()==evt.VK_ENTER){  
            int i=0;
            while(i<1){
                this.person=Person.login(txt_username.getText(),txt_password.getText());
                i++;
            }
            String sql = "SELECT * FROM PERSON WHERE Person_ID =?";
            String temp;

            try{
                Connection con=ConnectionBuilder.getConnection();
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,""+person.getPersonId());
                ResultSet rs=pst.executeQuery();
                if (rs.next()) {
                    temp = rs.getString("Person_TYPE");
                    this.setVisible(false);
                    if(temp.equalsIgnoreCase("student")){
                        home = new BookingHome(person);
                        home.setVisible(true);
                        System.out.println(person);
                    }
                    else if(temp.equalsIgnoreCase("admin")){
                        adHome = new Admin(this.person);
                        adHome.setVisible(true);
                        System.out.println(person);
                    }
                }
                con.close();
            }catch(SQLException se){
                System.out.println(se);
            }
        
      }
        
        

    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JPanel wallpaper;
    private javax.swing.JLabel wallpaperLeft;
    // End of variables declaration//GEN-END:variables
}
