/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import Eway.model.ConnectionBuilder;
import Eway.model.Person;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class LoginGui extends javax.swing.JFrame {
    private Admin adHome; 
    private BookingHome home ;
    private Person person;
    /**
     * Creates new form LoginGui
     */
    public LoginGui() {
        initComponents();
        btn_exit.setBackground(new Color(255,255,255,0));
        
        this.setLocationRelativeTo(null);//setให้GUIแสดงตรงกลางจอคอม
    }

    public Person getPerson() {
        return person;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallpaperLeft = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        logoRoad = new javax.swing.JLabel();
        safeNight = new javax.swing.JLabel();
        logoBus = new javax.swing.JLabel();
        eway = new javax.swing.JLabel();
        wallpaperRight = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        logoPassword = new javax.swing.JLabel();
        logoUsername = new javax.swing.JLabel();
        tree1 = new javax.swing.JLabel();
        tree2 = new javax.swing.JLabel();
        tree3 = new javax.swing.JLabel();
        tree4 = new javax.swing.JLabel();
        tree5 = new javax.swing.JLabel();
        tree6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Safe Night Ride Care");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 166, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(204, 204, 204));
        welcome.setText("Welcome!");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel1.add(logoRoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        safeNight.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        safeNight.setForeground(new java.awt.Color(204, 255, 255));
        safeNight.setText("Safe Ride Night Care");
        jPanel1.add(safeNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel1.add(logoBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        eway.setFont(new java.awt.Font("Trajan Pro", 1, 16)); // NOI18N
        eway.setForeground(new java.awt.Color(204, 255, 255));
        eway.setText("E-way");
        jPanel1.add(eway, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        wallpaperRight.setBackground(new java.awt.Color(0, 58, 72));
        wallpaperRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(240, 240, 240));
        login.setText("Login to your account");
        wallpaperRight.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        password.setFont(new java.awt.Font("TH Sarabun New", 0, 30)); // NOI18N
        password.setForeground(new java.awt.Color(240, 240, 240));
        password.setText("Password");
        wallpaperRight.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        wallpaperRight.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 350, -1));
        wallpaperRight.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 350, -1));

        txt_username.setBackground(new java.awt.Color(0, 58, 72));
        txt_username.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        txt_username.setForeground(new java.awt.Color(240, 240, 240));
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        wallpaperRight.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 30));

        txt_password.setBackground(new java.awt.Color(0, 58, 72));
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(240, 240, 240));
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        wallpaperRight.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, 30));

        btn_login.setBackground(new java.awt.Color(209, 252, 255));
        btn_login.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 58, 72));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        wallpaperRight.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 126, 39));

        username.setFont(new java.awt.Font("TH Sarabun New", 0, 30)); // NOI18N
        username.setForeground(new java.awt.Color(240, 240, 240));
        username.setText("Username");
        wallpaperRight.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        wallpaperRight.add(logoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));
        wallpaperRight.add(logoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        wallpaperRight.add(tree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));
        wallpaperRight.add(tree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));
        wallpaperRight.add(tree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));
        wallpaperRight.add(tree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));
        wallpaperRight.add(tree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));
        wallpaperRight.add(tree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        wallpaperRight.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 30, -1));

        getContentPane().add(wallpaperRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 440, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        int i=0;
        while(i<1){
            this.person=Person.login(txt_username.getText(),txt_password.getText());
            i++;
        }
        String sql = "SELECT * FROM PERSON WHERE Person_ID =?";
        String temp;
        
        try{
            Connection con=ConnectionBuilder.getConnection();
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,""+person.getPersonId());
            ResultSet rs=pst.executeQuery();
            if (rs.next()) {
                temp = rs.getString("Person_TYPE");
                this.setVisible(false);
                if(temp.equalsIgnoreCase("student")){
                    home = new BookingHome(person);
                    home.setVisible(true);
                    System.out.println(person);
                }
                else if(temp.equalsIgnoreCase("admin")){
                    adHome = new Admin(this.person);
                    adHome.setVisible(true);
                    System.out.println(person);
                }
            }
        }catch(SQLException se){
            System.out.println(se);
        }
        
       
        
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
       int key=evt.getKeyCode();
       if(key==KeyEvent.VK_ENTER)
            txt_password.requestFocus();
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
            txt_username.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
      if(evt.getKeyCode()==evt.VK_ENTER){  
            int i=0;
            while(i<1){
                this.person=Person.login(txt_username.getText(),txt_password.getText());
                i++;
            }
            String sql = "SELECT * FROM PERSON WHERE Person_ID =?";
            String temp;

            try{
                Connection con=ConnectionBuilder.getConnection();
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,""+person.getPersonId());
                ResultSet rs=pst.executeQuery();
                if (rs.next()) {
                    temp = rs.getString("Person_TYPE");
                    this.setVisible(false);
                    if(temp.equalsIgnoreCase("student")){
                        home = new BookingHome(person);
                        home.setVisible(true);
                        System.out.println(person);
                    }
                    else if(temp.equalsIgnoreCase("admin")){
                        adHome = new Admin(this.person);
                        adHome.setVisible(true);
                        System.out.println(person);
                    }
                }
                con.close();
            }catch(SQLException se){
                System.out.println(se);
            }
        
      }
        
        

    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel eway;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel login;
    private javax.swing.JLabel logoBus;
    private javax.swing.JLabel logoPassword;
    private javax.swing.JLabel logoRoad;
    private javax.swing.JLabel logoUsername;
    private javax.swing.JLabel password;
    private javax.swing.JLabel safeNight;
    private javax.swing.JLabel tree1;
    private javax.swing.JLabel tree2;
    private javax.swing.JLabel tree3;
    private javax.swing.JLabel tree4;
    private javax.swing.JLabel tree5;
    private javax.swing.JLabel tree6;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel username;
    private javax.swing.JLabel wallpaperLeft;
    private javax.swing.JPanel wallpaperRight;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
