/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

/**
 *
 * @author hp
 */
public class Panel_BookingList extends javax.swing.JPanel {

    /**
     * Creates new form Panel_BookingList
     */
    public Panel_BookingList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_top = new javax.swing.JPanel();
        bookingList = new javax.swing.JLabel();
        panel_center = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pn_no = new javax.swing.JPanel();
        lb_no = new javax.swing.JLabel();
        pn_time = new javax.swing.JPanel();
        lb_time = new javax.swing.JLabel();
        pn_pickup = new javax.swing.JPanel();
        lb_pickup = new javax.swing.JLabel();
        pn_send = new javax.swing.JPanel();
        lb_send = new javax.swing.JLabel();
        showNo = new javax.swing.JTextField();
        showTime = new javax.swing.JTextField();
        showPickuo = new javax.swing.JTextField();
        showSend = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(567, 441));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top.setBackground(new java.awt.Color(0, 58, 72));
        panel_top.setForeground(new java.awt.Color(51, 0, 51));
        panel_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookingList.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        bookingList.setForeground(new java.awt.Color(204, 204, 204));
        bookingList.setText("Booking List");
        panel_top.add(bookingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 50));

        add(panel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        panel_center.setBackground(new java.awt.Color(0, 58, 72));
        panel_center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_center.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 528, 10));

        pn_no.setBackground(new java.awt.Color(204, 204, 204));

        lb_no.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_no.setForeground(new java.awt.Color(255, 255, 255));
        lb_no.setText("No.");

        javax.swing.GroupLayout pn_noLayout = new javax.swing.GroupLayout(pn_no);
        pn_no.setLayout(pn_noLayout);
        pn_noLayout.setHorizontalGroup(
            pn_noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_noLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_no, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_noLayout.setVerticalGroup(
            pn_noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_noLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_center.add(pn_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 30));

        pn_time.setBackground(new java.awt.Color(204, 204, 204));

        lb_time.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_time.setForeground(new java.awt.Color(255, 255, 255));
        lb_time.setText("Time");

        javax.swing.GroupLayout pn_timeLayout = new javax.swing.GroupLayout(pn_time);
        pn_time.setLayout(pn_timeLayout);
        pn_timeLayout.setHorizontalGroup(
            pn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_time)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pn_timeLayout.setVerticalGroup(
            pn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_timeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_center.add(pn_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 30));

        pn_pickup.setBackground(new java.awt.Color(204, 204, 204));

        lb_pickup.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_pickup.setForeground(new java.awt.Color(255, 255, 255));
        lb_pickup.setText("Pickup Place");

        javax.swing.GroupLayout pn_pickupLayout = new javax.swing.GroupLayout(pn_pickup);
        pn_pickup.setLayout(pn_pickupLayout);
        pn_pickupLayout.setHorizontalGroup(
            pn_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pickupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pn_pickupLayout.setVerticalGroup(
            pn_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pickupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_center.add(pn_pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, 30));

        pn_send.setBackground(new java.awt.Color(204, 204, 204));

        lb_send.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        lb_send.setForeground(new java.awt.Color(255, 255, 255));
        lb_send.setText("Send Place");

        javax.swing.GroupLayout pn_sendLayout = new javax.swing.GroupLayout(pn_send);
        pn_send.setLayout(pn_sendLayout);
        pn_sendLayout.setHorizontalGroup(
            pn_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pn_sendLayout.setVerticalGroup(
            pn_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sendLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_center.add(pn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 30));

        showNo.setEditable(false);
        showNo.setBackground(new java.awt.Color(204, 204, 204));
        showNo.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        panel_center.add(showNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 110));

        showTime.setEditable(false);
        showTime.setBackground(new java.awt.Color(204, 204, 204));
        showTime.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        panel_center.add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 110));

        showPickuo.setEditable(false);
        showPickuo.setBackground(new java.awt.Color(204, 204, 204));
        showPickuo.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        panel_center.add(showPickuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 150, 110));

        showSend.setEditable(false);
        showSend.setBackground(new java.awt.Color(204, 204, 204));
        showSend.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        panel_center.add(showSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, 110));

        btn_clear.setBackground(new java.awt.Color(103, 197, 233));
        btn_clear.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        panel_center.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 110, 40));

        add(panel_center, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
    
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingList;
    private javax.swing.JButton btn_clear;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_no;
    private javax.swing.JLabel lb_pickup;
    private javax.swing.JLabel lb_send;
    private javax.swing.JLabel lb_time;
    private javax.swing.JPanel panel_center;
    private javax.swing.JPanel panel_top;
    private javax.swing.JPanel pn_no;
    private javax.swing.JPanel pn_pickup;
    private javax.swing.JPanel pn_send;
    private javax.swing.JPanel pn_time;
    private javax.swing.JTextField showNo;
    private javax.swing.JTextField showPickuo;
    private javax.swing.JTextField showSend;
    private javax.swing.JTextField showTime;
    // End of variables declaration//GEN-END:variables
}
