/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import Eway.model.Booking;
import Eway.model.ConnectionBuilder;
import Eway.model.Person;
import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */

public class Panel_RoundTable extends java.awt.Panel {
    
    Person person;
    /**
     * Creates new form BookingHomepage
     */
    public void setPerson(Person person){
        this.person=person;
    }
    public Panel_RoundTable() {
        initComponents();
        btn_booking.setBackground(new Color(255,255,255,0));
        txt_etctime.setBackground(new Color(255,255,255,0));
        txt_phone.setBackground(new Color(255,255,255,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbbox_time = new javax.swing.JComboBox<>();
        txt_etctime = new javax.swing.JTextField();
        cbbox_pickup = new javax.swing.JComboBox<>();
        cbbox_send = new javax.swing.JComboBox<>();
        txt_phone = new javax.swing.JTextField();
        btn_booking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(576, 441));
        setPreferredSize(new java.awt.Dimension(576, 441));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbbox_time.setBackground(new java.awt.Color(251, 227, 227));
        cbbox_time.setFont(new java.awt.Font("TH Sarabun New", 0, 22)); // NOI18N
        cbbox_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "23.00", "00.00", "01.00", "Etc." }));
        cbbox_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_timeActionPerformed(evt);
            }
        });
        jPanel2.add(cbbox_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, 30));

        txt_etctime.setBackground(new java.awt.Color(204, 204, 204));
        txt_etctime.setFont(new java.awt.Font("TH Sarabun New", 0, 22)); // NOI18N
        txt_etctime.setForeground(new java.awt.Color(251, 227, 227));
        txt_etctime.setText("etc.");
        txt_etctime.setToolTipText("");
        txt_etctime.setBorder(null);
        txt_etctime.setCaretColor(new java.awt.Color(251, 227, 227));
        txt_etctime.setDisabledTextColor(new java.awt.Color(251, 227, 227));
        txt_etctime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_etctimeFocusGained(evt);
            }
        });
        txt_etctime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_etctimeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_etctime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 80, 30));

        cbbox_pickup.setBackground(new java.awt.Color(251, 227, 227));
        cbbox_pickup.setFont(new java.awt.Font("TH Sarabun New", 0, 22)); // NOI18N
        cbbox_pickup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIT", "ตึกอธิการ", "ตึก14ชั้น", "หอหญิง", "หน้า7-11วิศวะ", "ตึกแดง", "หน้าKFC", "FIBO", "หน้าตึกphysic", "LNG", "หน้าตึกวิศวะเคมี", "CB3", "CB4", "CB5(GMI)", "Learning Space" }));
        cbbox_pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_pickupActionPerformed(evt);
            }
        });
        jPanel2.add(cbbox_pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, 30));

        cbbox_send.setBackground(new java.awt.Color(251, 227, 227));
        cbbox_send.setFont(new java.awt.Font("TH Sarabun New", 0, 22)); // NOI18N
        cbbox_send.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "หอพัก myplace", "หอพัก myplace2", "คอนโดบ้านสวนธน", "หอพักธนบุญ", "the parque", "คอสโม เรสซิเดนซ์", "Residence", "หอพักรัชสิทธิ์", "TN modern place", "Library houze" }));
        cbbox_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_sendActionPerformed(evt);
            }
        });
        jPanel2.add(cbbox_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 30));

        txt_phone.setBackground(new java.awt.Color(204, 204, 204));
        txt_phone.setFont(new java.awt.Font("TH Sarabun New", 0, 22)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(251, 227, 227));
        txt_phone.setBorder(null);
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        jPanel2.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, 30));

        btn_booking.setBackground(new java.awt.Color(103, 197, 233));
        btn_booking.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_booking.setForeground(new java.awt.Color(34, 38, 75));
        btn_booking.setText("BOOKING");
        btn_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingActionPerformed(evt);
            }
        });
        jPanel2.add(btn_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\gib\\IT\\ปี1 เทอม2\\INT105 java\\Project\\E-way-project\\src\\icon\\roundtable.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingActionPerformed
        txt_etctime.setEditable(false);
        System.out.println(person);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date dt = new Date();
        String date = format.format(dt);
        String time = "";
        //--------------------------------Time----------------------------//
        int cbboxTime = cbbox_time.getSelectedIndex()+1;
        if(cbboxTime==1){//กรณีเลือกเวลา23.00
            time = " 23:00:00";
        }
        else if(cbboxTime==2){//กรณีเลือกเวลา23.00
            time = " 24:00:00";
        }
        else if(cbboxTime==3){//กรณีเลือกเวลา23.00
            time = " 01:00:00";
        }
        else{//กรณีเลือกเวลา23.00
            String showTime = txt_etctime.getText();
            CharSequence notAllowChar= "abcdefghijlmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+-/";
            if(!showTime.contains(notAllowChar)){
                String showHr = showTime.substring(0,2);//ตัดชั่วโมง
                String showMin = showTime.substring(3,5);//ตัดนาที
                time =" " +showHr+":"+showMin+":"+"00";//เก็บเวลาลงtimestamp
            }else{
                JOptionPane.showMessageDialog(null,"Enter Again please ");
                txt_etctime.requestFocus();
            }
        }
        //----------------------------------------------------------------//
        Person std = this.person;
        int receiveId = cbbox_pickup.getSelectedIndex()+1;
        int sendId = cbbox_send.getSelectedIndex()+16;
        //เก็บข้อมูลลงdb BOOKING

        ResultSet rs=null;
        try{
            String sql ="Select * From BOOKING Where Booking_DATE = CURDATE() AND Person_Id = ? ";
            Connection con = ConnectionBuilder.getConnection();
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1,person.getPersonId());
            rs=st.executeQuery();
            //con.close();
        }catch(SQLException e){
            System.out.println(e);
        }

        //------check that user enter all information--------
        String tel = txt_phone.getText();
        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcher = pattern.matcher(tel);
        if(matcher.matches()){
            System.out.println("Phone number valid");
        }
        try {
            if(!rs.next()){
                if(tel.length()==0||(tel.length()==10)&&matcher.matches()){
                    if(cbbox_time.getSelectedIndex()==3){
                        if((txt_etctime.getText()).equals("etc.")||(txt_etctime.getText()).equals("")){
                            JOptionPane.showMessageDialog(this,"Please enter time booking");
                            txt_etctime.requestFocus();
                        }else
                        new Booking(time, date, std, receiveId, sendId,std.getTel());
                        JOptionPane.showMessageDialog(this,"Successed, You can see your booking in Booking List.");
                    }
                    else if(cbbox_time.getSelectedIndex()!=3 &&!(txt_etctime.getText()).equals("etc.")){
                        JOptionPane.showMessageDialog(this,"Choose time again!");
                        txt_etctime.setText("etc.");
                    }
                    else{
                        if(txt_phone.getText().equals("")){
                            Booking book = new Booking(time, date, std, receiveId, sendId,std.getTel());
                            JOptionPane.showMessageDialog(this,"Successed, You can see your booking in Booking List.");
                        }else{
                            Booking book = new Booking(time, date, std, receiveId, sendId,txt_phone.getText());
                            JOptionPane.showMessageDialog(this,"Successed, You can see your booking in Booking List.");
                        }
                    }

                }else{
                    JOptionPane.showMessageDialog(this,"Please check your phone number again");
                    txt_phone.requestFocus();
                }
            }else
            JOptionPane.showMessageDialog(this,"You've book already kub");

        } catch (SQLException ex) {
            System.out.println(ex);;
        }

    }//GEN-LAST:event_btn_bookingActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void cbbox_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbox_sendActionPerformed

    private void cbbox_pickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_pickupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbox_pickupActionPerformed

    private void txt_etctimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_etctimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_etctimeActionPerformed

    private void txt_etctimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_etctimeFocusGained
        txt_etctime.setText("");
        txt_etctime.setForeground(Color.black);
    }//GEN-LAST:event_txt_etctimeFocusGained

    private void cbbox_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_timeActionPerformed
        if(cbbox_time.getSelectedIndex()==3)
        txt_etctime.setEditable(true);
        else
        txt_etctime.setEditable(false);
    }//GEN-LAST:event_cbbox_timeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_booking;
    private javax.swing.JComboBox<String> cbbox_pickup;
    private javax.swing.JComboBox<String> cbbox_send;
    private javax.swing.JComboBox<String> cbbox_time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_etctime;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
