/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import Eway.model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Panel_EditProfile extends javax.swing.JPanel {
    Person person;
    /**
     * Creates new form Panel_EditProfile
     */
    public void setPerson(Person person){
        this.person=person;
        txt_name.setText(person.getStuName());
        txt_email.setText(person.getEMAIL());
        txt_faculty.setText(person.getBranchOf());
        txt_branchOf.setText(person.getBranchOf());
        
    }
    public Panel_EditProfile(Person person) {
        initComponents();
        this.person=person;
        txt_branchOf.setText(person.getBranchOf());
        txt_name.setText(person.getStuName());
        txt_faculty.setText(person.getFaculty());
        txt_email.setText(person.getEMAIL());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_top = new javax.swing.JPanel();
        editProfile = new javax.swing.JLabel();
        panel_center = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        name = new javax.swing.JLabel();
        faculty = new javax.swing.JLabel();
        branchOf = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_faculty = new javax.swing.JTextField();
        txt_branchOf = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top.setBackground(new java.awt.Color(0, 58, 72));
        panel_top.setForeground(new java.awt.Color(51, 0, 51));
        panel_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editProfile.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        editProfile.setForeground(new java.awt.Color(204, 204, 204));
        editProfile.setText("Edit your profile");
        panel_top.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 50));

        add(panel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        panel_center.setBackground(new java.awt.Color(0, 58, 72));
        panel_center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_center.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 528, 10));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        name.setForeground(new java.awt.Color(240, 240, 240));
        name.setText("Name : ");
        panel_center.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 50));

        faculty.setBackground(new java.awt.Color(255, 255, 255));
        faculty.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        faculty.setForeground(new java.awt.Color(240, 240, 240));
        faculty.setText("Falculty : ");
        panel_center.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 50));

        branchOf.setBackground(new java.awt.Color(255, 255, 255));
        branchOf.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        branchOf.setForeground(new java.awt.Color(240, 240, 240));
        branchOf.setText("Branch of : ");
        panel_center.add(branchOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 50));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        email.setForeground(new java.awt.Color(240, 240, 240));
        email.setText("E-mail : ");
        panel_center.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, 50));

        btn_save.setBackground(new java.awt.Color(103, 197, 233));
        btn_save.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        panel_center.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, 40));

        txt_name.setBackground(new java.awt.Color(204, 204, 204));
        txt_name.setText("");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        panel_center.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 330, 30));

        txt_faculty.setBackground(new java.awt.Color(204, 204, 204));
        txt_faculty.setText("");
        txt_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facultyActionPerformed(evt);
            }
        });
        panel_center.add(txt_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 330, 30));

        txt_branchOf.setBackground(new java.awt.Color(204, 204, 204));
        txt_branchOf.setText("");
        panel_center.add(txt_branchOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 330, 30));

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setText("");
        panel_center.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 330, 30));

        add(panel_center, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String editName = txt_name.getText();
        String editFaculty = txt_faculty.getText();
        String editBranchOf = txt_branchOf.getText();
        String editEmail = txt_email.getText();
        
        person.editProfile(editName, editFaculty, editBranchOf, editEmail);
        JOptionPane.showMessageDialog(null,"update success");
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
     
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facultyActionPerformed
     
    }//GEN-LAST:event_txt_facultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branchOf;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel email;
    private javax.swing.JLabel faculty;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panel_center;
    private javax.swing.JPanel panel_top;
    private javax.swing.JTextField txt_branchOf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_faculty;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
