/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eway.GUI;

import Eway.model.Person;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Panel_EditProfile extends javax.swing.JPanel {
    Person person;
    /**
     * Creates new form Panel_EditProfile
     */
    public void setPerson(Person person){
        this.person=person;
        txt_name.setText(person.getStuName());
        txt_password.setText(person.getPassword());
        txt_phone.setText(person.getTel());
        txt_email.setText(person.getEMAIL());
        txt_faculty.setText(person.getFaculty());
        txt_branchOf.setText(person.getBranchOf());
        
        
        
    }
    public Panel_EditProfile(Person person) {
        initComponents();
        txt_name.setBackground(new Color(255, 255, 255, 0));
        txt_password.setBackground(new Color(255, 255, 255, 0));
        txt_phone.setBackground(new Color(255, 255, 255, 0));
        txt_email.setBackground(new Color(255, 255, 255, 0));
        txt_faculty.setBackground(new Color(255, 255, 255, 0));
        txt_branchOf.setBackground(new Color(255, 255, 255, 0));
        btn_save.setBackground(new Color(255, 255, 255, 0));
        this.person=person;
        txt_branchOf.setText(person.getBranchOf());
        txt_name.setText(person.getStuName());
        txt_faculty.setText(person.getFaculty());
        txt_email.setText(person.getEMAIL());
        txt_password.setText(person.getPassword());
        txt_phone.setText(person.getTel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_faculty = new javax.swing.JTextField();
        txt_branchOf = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setBackground(new java.awt.Color(0, 58, 72));
        t.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save.setBackground(new java.awt.Color(103, 197, 233));
        btn_save.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_save.setForeground(new java.awt.Color(34, 38, 75));
        btn_save.setText("SAVE");
        btn_save.setBorder(null);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        t.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 140, 30));

        txt_name.setBackground(new java.awt.Color(204, 204, 204));
        txt_name.setForeground(new java.awt.Color(251, 227, 227));
        txt_name.setText("");
        txt_name.setBorder(null);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        t.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 170, 30));

        txt_faculty.setBackground(new java.awt.Color(204, 204, 204));
        txt_faculty.setForeground(new java.awt.Color(251, 227, 227));
        txt_faculty.setText("");
        txt_faculty.setBorder(null);
        txt_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facultyActionPerformed(evt);
            }
        });
        t.add(txt_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, 30));

        txt_branchOf.setBackground(new java.awt.Color(204, 204, 204));
        txt_branchOf.setForeground(new java.awt.Color(251, 227, 227));
        txt_branchOf.setText("");
        txt_branchOf.setBorder(null);
        t.add(txt_branchOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, 30));

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setForeground(new java.awt.Color(251, 227, 227));
        txt_email.setText("");
        txt_email.setBorder(null);
        t.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 170, 30));

        txt_password.setBackground(new java.awt.Color(204, 204, 204));
        txt_password.setForeground(new java.awt.Color(251, 227, 227));
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        t.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 170, 30));

        txt_phone.setBackground(new java.awt.Color(204, 204, 204));
        txt_phone.setForeground(new java.awt.Color(251, 227, 227));
        txt_phone.setBorder(null);
        t.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\gib\\IT\\ปี1 เทอม2\\INT105 java\\Project\\E-way-project\\src\\icon\\editprofile.png")); // NOI18N
        t.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String editName = txt_name.getText();
        String editFaculty = txt_faculty.getText();
        String editBranchOf = txt_branchOf.getText();
        String editEmail = txt_email.getText();
        String editPassword = txt_password.getText();
        String editPhone = txt_phone.getText();
        if(editName.equals("") || editFaculty.equals("") || editBranchOf.equals("") ||
           editPassword.equals("") || editPhone.equals("")){
           JOptionPane.showMessageDialog(null,"please check again1");
        }
        else if(!editEmail.equals("")){
               System.out.println(editEmail);
               CharSequence allowChar= "@";
              
               if(editEmail.contains(allowChar)){
                    person.editProfile(editName, editPassword, editFaculty, editBranchOf, editPhone, editEmail, this.person);
                       JOptionPane.showMessageDialog(null,"update success");
                
               }else{
                     JOptionPane.showMessageDialog(null,"please check again2");
               }
                   
           }
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
     
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facultyActionPerformed
     
    }//GEN-LAST:event_txt_facultyActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel t;
    private javax.swing.JTextField txt_branchOf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_faculty;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
